export const SET_BANNER_IMAGES = 'SET_BANNER_IMAGES' // 设置Banner图片
export const SET_GRID_IMAGES = 'SET_GRID_IMAGES' // 设置Banner图片
export const SET_USER_TOKEN = 'SET_USER_TOKEN' // 设置用户Token
export const SET_GOODS_INFO = 'SET_GOODS_INFO'
export const SET_CATEGORY_INFO = 'SET_CATEGORY_INFO'
export const SET_USER_ID = 'SET_USER_ID'
export const SET_USER_CART = 'SET_USER_CART'
export const SET_USER_ADDRESS = 'SET_USER_ADDRESS'
export const SET_ORDER_ADDRESS = 'SET_ORDER_ADDRESS'
export const SET_USER_DETAIL = 'SET_USER_DETAIL'
export default {
  SET_BANNER_IMAGES,
  SET_GRID_IMAGES,
  SET_USER_TOKEN,
  SET_GOODS_INFO,
  SET_CATEGORY_INFO,
  SET_USER_ID,
  SET_USER_CART,
  SET_USER_ADDRESS,
  SET_USER_DETAIL,
  SET_ORDER_ADDRESS
}
